### ISSUE TITLE
Use "err" instead of "error"

### ISSUE THREAD

**Issue by railsmechanic** [thbar/golang-playground#1]
First, many thanks for your examples, but I recognized that you're using the variable name `error` in your error handling. This might work, but `error` is a built-in type. In order to prevent weird bugs, you should use **err** instead.

``` Go
file, err := os.Open("data/sample.csv")
if err != nil {
  panic(err)
}
```

**Comment by thbar** [comment]
I had no idea about that - thanks for letting me know! Will fix this next time I play around with go (hopefully soonish).

Thanks!!!

**Comment by railsmechanic** [comment]
I don't want to be a _smartass_ :) but I think it's great when more and more people use Go.
Here's the link to the documentation: http://golang.org/pkg/builtin/#error

**Comment by thbar** [comment]
Haha :-) no worries really, I truly appreciate your comment here. I really like Go, and will definitely use it more and more, hopefully in production on my SaaS app when the scale requires it.
